Numpy 2.0: `np.string_` -> `np.bytes_`
```
AttributeError: `np.string_` was removed in the NumPy 2.0 release.
Use `np.bytes_` instead.. Did you mean: 'strings'?
```